[workspace]
members = ["core_flow"]

[package]
name = "path-flow"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
core_flow = { path = "./core_flow" }
tokio = {version = "1.45.1", features = ["full"]}
