[package]
name = "core_flow"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = {version = "1.45.1", features = ["full"]}
uuid = {version = "1.17.0", features = ["v4"]}